### ISSUE TITLE
Adding support for command line snippets as well 

### ISSUE THREAD

**Issue by madrigal1** [maaslalani/nap#10]
Currently The flow of nap is excellent in creating code snippets from files. However it would be excellent if it could support saving and executing code snippets as well 

An example of this is "The-way" a cli comamnd line editor which has the option to create a code snippet like nap already does and a shell snippet which nap does not do. "The  way" also allows these shell snippets to be executed
https://github.com/out-of-cheese-error/the-way

There my feature request would be for you to add a new command;
1) nap exec <folder/snippet-name> 
  The command executes the contents of the snippet in the cmdline

**Comment by maaslalani** [comment]
Hi, it is possible to create snippets on the CLI:

```
nap folder/SnippetName.sh < script.sh
```

And you can likely pipe this snippet into bash to execute it.

```
nap folder/SnippetName.sh | bash
```

Let me know if I am missing something!

**Comment by madrigal1** [comment]
Great solution here are the short commands i created to quickly handle shell snippets and give it similar functionality to snippet managers like pet(https://github.com/knqyf263/pet) and the-way(https://github.com/out-of-cheese-error/the-way)

below shortcuts require 
1) gum 
2) xclip
3) bash

```
# select commmand and output snippet on terminal
function nsnip() {
  snippet_name=$(nap list | gum filter)
  sh -c "nap `printf %q "$snippet_name"`"
}

#select command and execute terminal
function nexec() { 
  snippet_name=$(nap list | gum filter)
  sh -c "nap `printf %q "$snippet_name"` | bash"
}

#select cmd and copy to clipboard
function nclip() { 
  snippet_name=$(nap list | gum filter)
  sh -c "nap `printf %q "$snippet_name"` | xclip -selection clipboard"
}

#save prev command in snippet
function nsave() {
  TMPFILE=$(mktemp /tmp/napcli-XXXXX)
  trap "rm -f $TMPFILE" EXIT
  PREV=$(fc -lrn | head -n 1)
  # snippet_name=$(gum input)
  snippet_name=$(gum input --prompt="Name of snippet: " --value="shell/newcmd" --width=80)
  echo "New Snippet name: ${snippet_name}"
  echo "Saved cmd: ${PREV}"
  echo $PREV >> $TMPFILE  # Append some text to the file
  sh -c "nap `printf %q "$snippet_name"` < `printf %q "$TMPFILE"`"                    # Print the contents of the file
  rm $TMPFILE    
}

```

**Comment by madrigal1** [comment]
For future ref:
Recommended way

```
alias napclip="nap $(nap list | gum filter) | xclip -selection clipboard"
alias napexec="nap $(nap list | gum filter) | bash"
alias napsave="gum write | nap $(gum input --placeholder folder/snippet.ext)"
```
