### ISSUE TITLE
Vim/Neovim plugin support

### ISSUE THREAD

**Issue by taigrr** [maaslalani/nap#12]
It would be nice to have a simple vim command to jump into nap, select a snippet, and drop it into the current file at the cursor location.

Alternatively, instructions on how nap might integrate with existing snippet engines could suffice

**Comment by sarca571ca** [comment]
You can use `:read !nap string` and it'll insert it at your cursor. Just means you have to save your snippets in an intuitive way. For example, if I want to add a "go slice" to my code id save that snippet as go-slice and in nvim i'd type `:read !nap go-slice`.

**Comment by maaslalani** [comment]
As @sarca571ca mentioned, `nap`'s command line utility is meant to be used in any editor. So, I most likely won't be building a neovim plugin for it.

That being said, it would be very cool to see a snippet's plugin use `nap` as a source of snippets, though.
