### ISSUE TITLE
No colors in tmux

### ISSUE THREAD

**Issue by v-p-b** [maaslalani/nap#21]
Coloring doesn't seem to work in tmux, at least in my config. Same terminal emulator config outside tmux works. 

I'm not sure this has to do with nap or bubbletea (or something else, syntax highlight works though), would be glad to debug further if you can provide some initial pointers about where to look.

**Comment by maaslalani** [comment]
Hey this may be an issue with your `tmux` config, are the following set in `tmux`?

```
set -g default-terminal 'xterm-256color'
set -g terminal-overrides ',xterm-256color:Tc'
```

**Comment by v-p-b** [comment]
This worked, thanks!
