### ISSUE TITLE
allow external editors to create contents in NAP_HOME

### ISSUE THREAD

**Issue by alperyilmaz** [maaslalani/nap#24]
**Is your feature request related to a problem? Please describe.**
If I use any other markdown editor to create a new note under NAP_HOME, it won't be recognized since `snippets.json` is not updated

**Describe the solution you'd like**
maybe a config option can be implemented, for example, "scan_folder_at_start: true" indicating that `nap` will scan the contents of the folder so that it can pick up changes (new files, renamed files, deleted files). I think this feature will allow `nap` to be used with many other markdown note-taking apps 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by maaslalani** [comment]
I entirely agree, this should be the default behaviour. Nap should scan for new snippets added (when the folder structure is implemented) and add them to the snippets.json file (since in the future we'll have things like notes for snippets)
