### ISSUE TITLE
No tilde expansion when parsing config

### ISSUE THREAD

**Issue by v-p-b** [maaslalani/nap#36]
**Describe the bug**
`~` is not expanded to `$HOME` when specifying the `home` parameter in the YAML config.

**To Reproduce**
1. Edit config.yaml to include `home: ~/.local/share/nap`
2. Start nap
3. Observe that only the default snippet is shown
4. Exit nap
5. Observe that a new directory named `~` appeared in the CWD

**Expected behavior**
The `~` character is expaded to `$HOME`, the contents of /home/username/.local/share/nap is read by nap.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Shell: zsh
 - nap installed via go install 

**Smartphone (please complete the following information):**

N/A

**Additional context**

Tilde expansion is expected based on the current README. I won't outrule the possibility that something is messed up with my shell as this is a migrated install from a different system.

**Comment by maaslalani** [comment]
This should be fixed thanks to the awesome @jolheiser! 

Please let us know if it's working now :)

**Comment by v-p-b** [comment]
This did the trick, thank you!
