### ISSUE TITLE
Help flags do not work

### ISSUE THREAD

**Issue by saccarosium** [maaslalani/nap#48]
**Describe the bug**
When I call nap with `-h` and `--help` flags doesn't do anything. Exits with 0 code.

**To Reproduce**
1. Open termanal
2. Type `nap --help`
3. Press Enter
4. Nothing show up

**Expected behavior**
An help menu show up. Seeing the source code the is already one.

**Screenshots**
<img width="329" alt="Screenshot 2023-04-18 at 10 14 32" src="https://user-images.githubusercontent.com/96259932/232715140-ecaba8f8-bd15-4891-85a9-142f95f259b0.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Ventura (13.3.1)
 - Kernel: Darwin Kernel Version 22.4.0

**Additional context**
I'm using tmux but the problem persist even outside of it.

**Comment by jolheiser** [comment]
The `--help` flag is not in a released version yet.

It was introduced in https://github.com/maaslalani/nap/commit/e0ce0438e9db9e9c5fea86fbab2cec0d363c6fb9 and should be in the next release 🙂
