### ISSUE TITLE
The ability to modularize the snippets themselves

### ISSUE THREAD

**Issue by z0xyz** [maaslalani/nap#50]
First, I'd like to thank you for your effort on this project. However there're few areas that I find worth enhancing.
- The ability search through snippets themselves.
- Easily create new folder. Already mentioned in this [issue](https://github.com/maaslalani/nap/issues/14).
- Having separate kind of boxes on the right-hand side for the code snippets, which can be searched/referenced via their comment, or generally cycled through (Rather than a pager for an entire file).

**Comment by kugarocks** [comment]
I have make a fork version for the third point. You can checkout [Markdown Finder](https://github.com/kugarocks/markdown-finder) which is a tool for quickly locating code snippets in Markdown files. Use `---` to divide sections of a Markdown file, making it easy to copy code from each section. @kqvanity @maaslalani
