### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by nut-3** [maaslalani/nap#9]
Hello.
First, thanks for the app, I really enjoy it.
Second, for my own convenience, I created an AUR-package for bin distribution - https://aur.archlinux.org/packages/nap-bin.
Hope you don't mind it. Anyway, I can pass you maintainer's rights anytime, if you wish.
PS
Nap is quite a common project name. AUR already has nap-git and nap, and there are quite a bin `nap`s on github. Maybe consider renaming project to something more unique and self-explanatory?

**Comment by maaslalani** [comment]
Thank you so much for packaging this for the AUR!

I agree, and I may rename the project in the future.

**Comment by danielwerg** [comment]
What about `nap-go`?

Since `nap` last release was over 2 years, would be great to have git package.
